version: '3.9'
services:
  user-cycle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - ENV_ID=prod
      - DD_ENV=prod
      - DD_PROFILING_ENABLED=true
    restart: always
    network_mode: host