version: '3.9'
services:
  user-cycle:
    build:
      context: .
      dockerfile: Dockerfile
    command: "node /app/app/user-cycle.js"
    ports:
      - 4000:4000
    environment:
      - ENV_ID=prod
    restart: always
    network_mode: host